name: flupass
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.5+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  shared_preferences: ^2.2.3
  local_auth: ^2.1.7
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  csv: ^5.1.1
  file_picker: ^8.0.5
  share_plus: ^10.0.0
  google_fonts: ^6.2.1
  encrypt: ^5.0.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/appicon/

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: assets/appicon/flupass.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/flupass-splash.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/splash/flupass-splash.png
