name: flupass
description: "Secure password manager"
publish_to: 'none'
version: 1.1.8+11

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  shared_preferences: ^2.2.3
  local_auth: ^3.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  csv: ^6.0.0
  file_picker: ^10.3.10
  share_plus: ^10.1.4
  google_fonts: ^8.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/appicon/

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: assets/appicon/flupass.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/flupass-splash.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/splash/flupass-splash.png
